version: '3.7'

services:
  node:
    image: node:14
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    command: node app.js
    working_dir: /home/node/app

volumes: 
  node_modules:
    driver: local
