version: '3.7'

services:
  node:
    image: node:14
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - development
      - DEBUG='app:*'
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    command: /home/node/app/node_modules/.bin/nodemon app.js

volumes: 
  node_modules:
    driver: local
